### ISSUE TITLE
Scheme structure

### ISSUE THREAD

**Issue by katepolak** [kepano/flexoki-neovim#1]
Continuing the discussion from https://github.com/kepano/flexoki/issues/48, before we really get started on the new repo I think we decide whether we want to keep the colorgen utility or not, and if not what structure for the scheme we want to go with.

Personally I don't see any value in using colorgen, but it's not something I should be making decisions about on my own, hence this issue.

**Comment by katepolak** [comment]
@kepano how long do you think I should wait before just going ahead and doing it on my own? Don't really wanna do that without your approval, since I am not the original author of the port.

Tagging @dinocosta in case you haven't see the repo yet.

**Comment by kepano** [comment]
Personally I don't have strong opinions on this. I can copy over the files from the main repo to this one, if that helps? We can start there, or you can submit a first PR here. What do you prefer?

**Comment by dinocosta** [comment]
Thank you for opening this issue @polak-jan 👍 

Personally, as far as I know https://github.com/LunarVim/colorgen-nvim does not support creating a colorscheme with multiple variants. As such, I believe we can remove it from the original project, otherwise we'd probably need to create one colorscheme for each of the variants and them "merge" them altogether?

I'm not familiar with the structure of a lot of colorschemes in NeoVim but I took a quick glance at https://github.com/rose-pine/neovim and it looks simple enough that we could try to mimic it. What do you think @polak-jan ?

Lastly, how do you all feel about a change in naming? Right now, with the current NeoVim colorscheme we have:
* `vim.cmd.colorscheme 'flexoki'` - uses the dark variant
* `vim.cmd.colorscheme 'flexoki-light'` - uses the light variant

What do you think about updating to `flexoki-dark` and `flexoki-light`? I believe that's also what [VSCode's extension uses](https://github.com/kepano/flexoki/tree/main/vscode) .

**Comment by katepolak** [comment]
Sounds good to me. So for now I would remove colorgen, rename the variants and get on with fixing issues. And keep any bigger changes for after all that is up and running.

**Comment by dinocosta** [comment]
@polak-jan Sounds like a plan! Do you want to open a first PR moving the code from https://github.com/kepano/flexoki/tree/main/neovim to this repo? 

Afterwards we can start tackling these changes 👍

**Comment by katepolak** [comment]
Will do. Probably early tomorrow.

**Comment by katepolak** [comment]
Turns out that GitHub really doesn't like the repo being empty and won't even let me fork it or make a PR. So could someone with actual permissions please add an empty readme or something like that so I could post the PR?

**Comment by kepano** [comment]
@polak-jan Ah! Makes sense. Done.

**Comment by katepolak** [comment]
I have also started slowly porting the theme to the same-ish structure as the rose-pine them that was linked above. Sadly this can't really be done 1 to 1 as the original dark and light themes not only had different palettes but also a few differences in how the palette mapped to the highlight groups. And we need that mapping to be the same across all variants.

Will put up a draft PR in a minute with the changes.

**Comment by katepolak** [comment]
Hey. Sorry for the massive delay. First I was waiting for someone else to reply, @dinocosta especially since he is designated as a "collaborator" unlike me, and I didn't want to put it too much work without an opinion from him, and then I was out with covid for a few weeks.

@kepano, how do you want me to proceed, should I just continue with what I was working on and do it all my way and you will approve the merge for me, or should I wait for @dinocosta?

**Comment by kepano** [comment]
@polak-jan I have added you as a collaborator. Unfortunately I don't have much time at the moment to evaluate changes, and I'm also not familiar enough with Neovim. You should go forward with your approach. The Flexoki ports for Sublime Text and VS Code should provide good reference.

I added the following code sample to the main repo
https://github.com/kepano/flexoki/blob/main/_samples/typescript.ts

You can also scroll down to the mappings for syntax highlighting
https://stephango.com/flexoki

**Comment by hydroakri** [comment]
Sorry for my rude and disturb.
I am using [catppuccin/nvim](https://github.com/catppuccin/nvim), and I found that the compatibility to other plugins is great. Is it possible to fork and override the color scheme of catppuccin. That way you don't have to do repetitive work.
Maybe you can fork it and change the color `lua/catppuccin/palettes`
In fact, I have already done for my own config:
```
{
			"catppuccin/nvim",
			name = "catppuccin",
			opts = {
				background = { -- :h background
					light = "latte",
					dark = "mocha",
				},
				-- transparent_background = true,
				color_overrides = {
					all = {
						rosewater = "#CE5D97",
						flamingo = "#A02F6F",
						pink = "#8B7EC8",
						mauve = "#5E409D",
						red = "#D14D41",
						maroon = "#AF3029",
						peach = "#D0A215",
						yellow = "#AD8301",
						green = "#879A39",
						teal = "#66800B",
						sky = "#3AA99F",
						sapphire = "#24837B",
						blue = "#4385BE",
						lavender = "#205EA6",
					},
					mocha = {
						text = "#FFFCF0",
						subtext1 = "#F2F0E5",
						subtext0 = "#E6E4D9",
						overlay2 = "#DAD8CE",
						overlay1 = "#CECDC3",
						overlay0 = "#B7B5AC",
						surface2 = "#878580",
						surface1 = "#6F6E69",
						surface0 = "#575653",
						base = "#100F0F",
						mantle = "#1C1B1A",
						crust = "#282726",
					},
					latte = {
						text = "#100F0F",
						subtext1 = "#1C1B1A",
						subtext0 = "#282726",
						overlay2 = "#343331",
						overlay1 = "#403E3C",
						overlay0 = "#575653",
						surface2 = "#6F6E69",
						surface1 = "#878580",
						surface0 = "#B7B5AC",
						base = "#FFFCF0",
						mantle = "#F2F0E5",
						crust = "#E6E4D9",
					},
				},
		}
```
