### ISSUE TITLE
Lazy neovim window background is the same as text...

### ISSUE THREAD

**Issue by ys** [kepano/flexoki-neovim#4]
It works with other colorscheme, just not flexoki... Unsure why
<img width="947" alt="Screenshot 2023-11-28 at 11 50 49" src="https://github.com/kepano/flexoki-neovim/assets/483012/4c790f2e-5223-4185-a6a1-3f3ae032ba0a">

**Comment by katepolak** [comment]
Hey, sorry for the delay. The neovim port is sadly barely usable at this point and we were stuck for a few weeks for various reasons. Hopefully it will get better much quickly now.

**Comment by ys** [comment]
I don't know too much about how it works but I might try to learn a bit to assist :)

**Comment by katepolak** [comment]
Just merged the rework of the scheme into main, and while it doesn't have explicit support for Lazy yet the default highlight groups are enough to make it usable.

**Comment by eiiot** [comment]
I'm also running into issues w/ lazy just fyi

![CleanShot 2023-12-22 at 23 05 59@2x](https://github.com/kepano/flexoki-neovim/assets/39346975/66d77bb8-3485-415d-8cc4-65b1e1e0f5cc)

**Comment by katepolak** [comment]
That's definitely not an issue with Lazy, the Lazy window isn't opened in that screenshot.
I am guessing the issue you are talking about is the green column. I can't really diagnose it without knowing what plugins you are using. The theme currently has a fairly limited plugin support, while I am slowly adding them one by one. If you send over a list of your plugins I can can take a look at adding support for them over the next few days.

**Comment by eiiot** [comment]
Ah, you're right, sorry! Assumed the original was talking about lazy as a whole. The plugin is [mini.indentscope](https://github.com/echasnovski/mini.indentscope), installed by default w/ lazy.

**Comment by katepolak** [comment]
Ah, you mean Lazy as in the distribution, not Lazy the package manager.

But I don't think mini.indentscope is the issue either. I have already added manual support for mini.nvim and I have the indentscope module enabled myself and it looks just fine for me.
