### ISSUE TITLE
Light theme doesn't appear to set the background option properly

### ISSUE THREAD

**Issue by wpkelso** [kepano/flexoki-neovim#5]
When `flexoki-light` is used as the color theme, the `background` option appears to be still set to `dark` (verified through `echo &background`), which doesn't seem to be right

**Comment by katepolak** [comment]
Hey, sorry for the delay. The neovim port is sadly barely usable at this point and we were stuck for a few weeks for various reasons. Hopefully it will get better much quickly now.

**Comment by katepolak** [comment]
Just merged a complete rework of the scheme. Plus a fix for this. I personally don't use light themes but I checked most common things with it set and it looked fine. Would be appriciated if you could give it another go and report any issues it still has.

**Comment by wpkelso** [comment]
Everything appears to work as expected now, thanks!
